<article class="arabic">
    <div class="resume">
        <div class="resume_left">
            <div class='r-hex'>
                <div class='r-hex-inner'>
                    <div class='r-hex-inner-2'></div>
                </div>
            </div>
            <div class="resume_content">
                <div class="resume_item resume_info">
                    <div class="title-name">
                        <p class="bold"> محمد حسنين </p>
                        <p class="regular">Full Stack Web Developer</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fas fa-map-signs"></i>
                            </div>
                            <div class="data">
                                95 Avenue de la Résistance, Le Raincy<br /> FRANCE
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-mobile-alt"></i>
                            </div>
                            <div class="data">
                                07 67 93 38 18
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-envelope"></i>
                            </div>
                            <div class="data">
                                mohammed.tareq.hassanien@hotmail.com
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-weebly"></i>
                            </div>
                            <div class="data">
                                <a href="https://mohammedhassanein.herokuapp.com/">mohammedhassanein.herokuapp.com</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-chart-bar"></i> Skills</p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                HTML
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per">90%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                CSS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per">90%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                SASS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per">90%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                JS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per">85%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                jQuery
                            </div>
                            <div class="skill_progress">
                                <span style="width: 88%;"></span>
                            </div>
                            <div class="skill_per">88%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                PHP
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per">90%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Vue.js
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per">85%</div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-language"></i> languages </p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                Arabic
                            </div>
                            <div class="skill_progress">
                                <span style="width: 100%;"></span>
                            </div>
                            <div class="skill_per">100%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                English
                            </div>
                            <div class="skill_progress">
                                <span style="width: 95%;"></span>
                            </div>
                            <div class="skill_per">95%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                French
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per">90%</div>
                        </li>
                    </ul>
                </div>

                <div class="resume_item resume_social">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-hashtag"></i> Social media</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fab fa-facebook-square"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Facebook</p>
                                <a href="https://www.facebook.com/profile.php?id=582452558">Mohammed-Tareq</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-twitter-square"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Twitter</p>
                                <a href="https://twitter.com/momed9999?s=08"> @momed9999</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-instagram"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Instagram</p>
                                <a href="https://www.instagram.com/momed999/">momed999</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-linkedin"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Linkedin</p>
                                <a
                                    href="https://www.linkedin.com/in/mohammed-hassanein-4a9b172a">linkedin.com/in/mohammed-hassanein-dev</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-github"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Github</p>
                                <a href="https://github.com/Tiko8690">Tiko8690</a>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="resume_right">
            <div class="resume_item resume_about">
                <div class="title">
                    <p class="bold"> <i class="fas fa-user"></i> ABOUT </p>
                </div>
                <p> Certified full-stack web developer with experience in HTLM, CSS, JavaScript, PHP, Vue.js, JQuery
                    and MySQL. Work on customer needs analysis, project development and implementation design.
                </p>
            </div>
            <div class="resume_item resume_work">
                <div class="title">
                    <p class="bold"> <i class="fas fa-suitcase"></i> الخبرة المهانية </p>
                </div>
                <ul>
                    <li>
                        <div class="date">2020</div>
                        <div class="info">
                            <p class="semi-bold">Full Stack Web Developer </p>
                            <p>3W Academy – Web education– Paris, France</p>
                            <ul class="competence">
                                <li>Analyze the client's needs.</li>
                                <li>Write a Technical Requirement Specification (STB).</li>
                                <li>Carry out studies and IT developments.</li>
                                <li>Define the human, material and financial resources of a project. </li>
                                <li>Establish specifications. </li>
                                <li>Plan the stages of a project.</li>
                                <li> Create and develop applications / websites with database connection .
                                </li>
                                <li>Intervene in IT management. </li>


                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="date">2019 - 2020</div>
                        <div class="info">
                            <p class="semi-bold">Accounting Manager</p>
                            <p>SARL-S.T.F - Paris, France</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2012 - 2017</div>
                        <div class="info">
                            <p class="semi-bold">Chief Financial Officer</p>
                            <p>LOGISTICS INTERNATIONAL OUTSOURCING NETWORKING SERVICES (LIONS) - Alexandria, Egypt </p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2010 - 2012</div>
                        <div class="info">
                            <p class="semi-bold">Accounting Manager</p>
                            <p>INTER LOG INTERNATIONAL LOGISTICS - Alexandria, Egypt </p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2007 - 2017</div>
                        <div class="info">
                            <p class="semi-bold">Chartered Accountant</p>
                            <p>Tareq Hassanein Chartered Accountant Office - Alexandria, Egypt </p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_education">
                <div class="title">
                    <p class="bold"> <i class="fas fa-graduation-cap"></i> التعليم </p>
                </div>
                <ul>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Web Developer ( 3W Academy )</p>
                            <p>Web Developer , Web / multimedia management and webmaster</p>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Faculty of Commerce – University of Alexandria</p>
                            <p>Bachelor of commerce (BAC + 4 )</p>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Victory Collège </p>
                            <p>Baccalaureate, Scientific </p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_hobby">
                <div class="title">
                    <p class="bold"> <i class="fas fa-star"></i> الهوايات </p>
                </div>
                <ul>
                    <li>
                        <i class="fas fa-book"></i>
                        <p>Read books</p>
                    </li>
                    <li><i class="fas fa-gamepad"></i>
                        <p>Play video games</p>
                    </li>
                    <li><i class="fas fa-music"></i>
                        <p>الموسيقى</p>
                    </li>
                    <li><i class="fas fa-futbol"></i>
                        <p>كرة القدم </p>
                    </li>
                    <li><i class="fas fa-plane"></i>
                        <p>السفر </p>
                    </li>
                </ul>
            </div>
        </div>
    </div>


</article>