<article>
    <div class="resume">
        <div class="resume_left">
            <div class='r-hex'>
                <div class='r-hex-inner'>
                    <div class='r-hex-inner-2'></div>
                </div>
            </div>
            <div class="resume_content">
                <div class="resume_item resume_info">

                    <div class="title-name">
                        <p class="bold">Mohammed HASSANEIN</p>
                        <p class="regular">Full Stack Web Developer</p>
                    </div>
                    <div class="title">
                        <p class="bold details"> <i class="fas fa-info-circle"></i> Details</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fas fa-map-signs"></i>
                            </div>
                            <div class="data">
                                Paris, FRANCE
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-mobile-alt"></i>
                            </div>
                            <div class="data">
                                (+33)
                                07-67-93-38-18
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-envelope"></i>
                            </div>
                            <div class="data">
                                mohammed.tareq.hassanien@hotmail.com
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-chart-bar"></i> Skills</p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                HTML
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                CSS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                SASS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                JS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                jQuery
                            </div>
                            <div class="skill_progress">
                                <span style="width: 88%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                PHP
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Vue.js
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Symfony
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Node.js
                            </div>
                            <div class="skill_progress">
                                <span style="width: 92%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                WordPress
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-language"></i> languages </p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                Arabic
                            </div>
                            <div class="skill_progress">
                                <span style="width: 98%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                English
                            </div>
                            <div class="skill_progress">
                                <span style="width: 98%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                French
                            </div>
                            <div class="skill_progress">
                                <span style="width: 95%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                    </ul>
                </div>

                <div class="resume_item resume_social">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-hashtag"></i> Links</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fab fa-linkedin"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Linkedin</p>
                                <a href="https://www.linkedin.com/in/mohammed-hassanein-4a9b172a">linkedin.com/in/mohammed-hassanein-dev</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-github"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Github</p>
                                <a href="https://github.com/M-HASSANEIN">M-HASSANEIN</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-weebly"></i>
                            </div>
                            <div class="data">
                                <a href="https://mohammedhassanein.herokuapp.com/">mohammedhassanein.herokuapp.com</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-weebly"></i>
                            </div>
                            <div class="data">
                                <a href="http://mohammedhassaneinportfolio.herokuapp.com//">mohammedhassaneinportfolio.herokuapp.com</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="resume_right">
            <div class="resume_item resume_about">
                <div class="title">
                    <p class="bold"> <i class="fas fa-user"></i> Profile </p>
                </div>
                <p> I am a software developer with experience in HTLM, CSS, JavaScript and Node.js, PHP, My SQL and Symfony, Vue.js.
                    Passionate about the Web in all his forms, I am curious about new technologies and excited to find ways to implement them in my work.
                </p>
            </div>
            <div class="resume_item resume_work">
                <div class="title">
                    <p class="bold"> <i class="fas fa-suitcase"></i> Work experience </p>
                </div>
                <ul>
                    <li>
                        <div class="date">2021</div>
                        <div class="info">
                            <p class="semi-bold">Full Stack Web Developer </p>
                            <p>3W Academy – Web education– Paris, France</p>
                            <ul class="competence">
                                <li>Working with both front- and back-end languages.</li>
                                <li>Build fully-fledged platforms using a range of different technologies like HTML, CSS, JavaScript, PHP, Node.js, and frameworks like Vue.js and Symfony.</li>
                                <li>Building databases using MySQL and MongoDB.</li>
                                <li>Testing and debugging websites and applications.</li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="date">2020 - 2021 (4 Months) - Internship </div>
                        <div class="info">
                            <p class="semi-bold">Full Stack Web Developer </p>
                            <p>3W Academy – Web education– Paris, France</p>
                            <ul class="competence">
                                <li>Learning 5 technologies (HTML, CSS, PHP, JAVASCRIPT, MYSQL)</li>
                                <li>Analyze customer needs.</li>
                                <li>Establish technical specification documents.</li>
                                <li>Create and develop websites using CMS.</li>
                                <li>Integration of models and dynamically adapt them to the user's tools.</li>
                                <li>Develop web applications with JavaScript and PHP languages.</li>
                                <li>Linking applications to Databases using SQL.</li>
                                <li>Determine the phases and procedures of technical and functional tests of computer
                                    programs and applications.</li>
                                <li>Analyze and solve technical problems. </li>

                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="date">2019 - 2020</div>
                        <div class="info">
                            <p class="semi-bold">Accounting Manager</p>
                            <p>SARL-S.T.F - Paris, France</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2012 - 2017</div>
                        <div class="info">
                            <p class="semi-bold">Chief Financial Officer</p>
                            <p>LOGISTICS INTERNATIONAL OUTSOURCING NETWORKING SERVICES (LIONS) - Alexandria, Egypt </p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2010 - 2012</div>
                        <div class="info">
                            <p class="semi-bold">Accounting Manager</p>
                            <p>INTER LOG INTERNATIONAL LOGISTICS - Alexandria, Egypt </p>
                        </div>
                    </li>

                </ul>
            </div>
            <div class="resume_item resume_education">
                <div class="title">
                    <p class="bold"> <i class="fas fa-graduation-cap"></i> Education</p>
                </div>
                <ul>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Web Developer ( 3W Academy )</p>
                            <p>Web Developer, Web / Multimedia Management and webmaster-Level 5 & EUROPE</p>
                            <P>(Developer-integrator certification in web application development) </P>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Faculty of Commerce</p>
                            <p>Bachelor of commerce</p>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Victory Collège </p>
                            <p>Baccalaureate, Scientific </p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_hobby">
                <div class="title">
                    <p class="bold"> <i class="fas fa-star"></i> Hobbies</p>
                </div>
                <ul>
                    <li>
                        <i class="fas fa-book"></i>
                        <p>Reading</p>
                    </li>
                    <li><i class="fas fa-gamepad"></i>
                        <p>Video games</p>
                    </li>
                    <li><i class="fas fa-music"></i>
                        <p>Music</p>
                    </li>
                    <li><i class="fas fa-futbol"></i>
                        <p>Football</p>
                    </li>
                    <li><i class="fas fa-plane"></i>
                        <p>Travel</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>


</article>
