<article>
    <div class="resume">
        <div class="resume_left">
            <div class='r-hex'>
                <div class='r-hex-inner'>
                    <div class='r-hex-inner-2'></div>
                </div>
            </div>
            <div class="resume_content">
                <div class="resume_item resume_info">
                    <div class="title-name">
                        <p class="bold">Mohammed HASSANEIN</p>
                        <p class="regular">Full Stack Développeur web</p>
                    </div>
                    <div class="title">
                        <p class="bold bold details"> <i class="fas fa-info-circle"></i> Détails</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fas fa-map-signs"></i>
                            </div>
                            <div class="data">
                                Paris, FRANCE
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-mobile-alt"></i>
                            </div>
                            <div class="data">
                                (+33)
                                07-67-93-38-18
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-envelope"></i>
                            </div>
                            <div class="data">
                                mohammed.tareq.hassanien@hotmail.com
                            </div>
                        </li>
                        <li>

                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-chart-bar"></i> Compétences</p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                HTML
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                CSS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                SASS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                JS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                jQuery
                            </div>
                            <div class="skill_progress">
                                <span style="width: 88%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                PHP
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Vue.js
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Symfony
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Node.js
                            </div>
                            <div class="skill_progress">
                                <span style="width: 92%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                WordPress
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-language"></i> langues</p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                Arabe
                            </div>
                            <div class="skill_progress">
                                <span style="width: 98%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Anglais
                            </div>
                            <div class="skill_progress">
                                <span style="width: 98%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Français
                            </div>
                            <div class="skill_progress">
                                <span style="width: 95%;"></span>
                            </div>
                            <div class="skill_per"></div>
                        </li>
                    </ul>
                </div>

                <div class="resume_item resume_social">
                    <div class="title">
                        <p class="bold"> <i class="fas fa-hashtag"></i> Liens</p>
                    </div>
                    <ul>

                        <li>
                            <div class="icon">
                                <i class="fab fa-linkedin"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Linkedin</p>
                                <a href="https://www.linkedin.com/in/mohammed-hassanein-4a9b172a">linkedin.com/in/mohammed-hassanein-dev</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-github"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Github</p>
                                <a href="https://github.com/M-HASSANEIN">M-HASSANEIN</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-weebly"></i>
                            </div>
                            <div class="data">
                                <a href="https://mohammedhassanein.herokuapp.com/">mohammedhassanein.herokuapp.com</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-weebly"></i>
                            </div>
                            <div class="data">
                                <a href="http://mohammedhassaneinportfolio.herokuapp.com//">mohammedhassaneinportfolio.herokuapp.com</a>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="resume_right">
            <div class="resume_item resume_about">
                <div class="title">
                    <p class="bold"> <i class="fas fa-user"></i> Profil </p>
                </div>
                <p> Développeur web expérimenté en HTLM, CSS, JavaScript, Node.js, PHP, MySQL, Symfony et Vue.
                    Je suis passionné par le Web et les nouvelles technologies que j'intègre dans mon travail.
                </p>
            </div>
            <div class="resume_item resume_work">
                <div class="title">
                    <p class="bold"> <i class="fas fa-suitcase"></i> Expériences Professionnelles</p>
                </div>
                <ul>
                    <li>
                        <div class="date">2021</div>
                        <div class="info">
                            <p class="semi-bold">Full Stack Web Developer </p>
                            <p>3W Academy – Web education– Paris, France</p>
                            <ul class="competence">
                                <li>Travailler avec les deux langues front-end et back-end.</li>
                                <li>Établir des plates-formes à part entière en utilisant une gamme de technologies différentes comme HTML, CSS, JavaScript, PHP, Node.js, et des frameworks comme Vue.js et Symfony.</li>
                                <li>Construire des bases de données en utilisant MySQL et MongoDB.</li>
                                <li>Tester et déboguer des sites Web et des applications.</li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="date">2020 - 2021 (4 mois) - Stage</div>
                        <div class="info">
                            <p class="semi-bold">Full Stack Développeur web </p>
                            <p>3W Academy – Web education– Paris, France</p>
                            <ul class="competence">

                                <li>Analyser les besoins du client.</li>
                                <li>Établir des documents de spécifications techniques.</li>
                                <li>Créer et développer des sites Web avec CMS.</li>
                                <li>Intégrer des modèles et les adapter dynamiquement aux outils de l’utilisateur.</li>
                                <li>Développer des applications web avec des langages JavaScript et PHP.</li>
                                <li>Lier des applications à des bases de données en utilisant SQL.</li>
                                <li>Déterminer les phases et les procédures des tests techniques et fonctionnels des programmes et applications informatiques.</li>
                                <li>Analyser et résoudre les problèmes techniques.</li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="date">2019 - 2020</div>
                        <div class="info">
                            <p class="semi-bold">Directeur Comptable</p>
                            <p>SARL-S.T.F - Paris, France</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2012 - 2017</div>
                        <div class="info">
                            <p class="semi-bold">Directeur Financier</p>
                            <p>LOGISTICS INTERNATIONAL OUTSOURCING NETWORKING SERVICES (LIONS) - Alexandrie, Egypte</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2010 - 2012</div>
                        <div class="info">
                            <p class="semi-bold">Directeur Comptable</p>
                            <p>INTER LOG INTERNATIONAL LOGISTICS - Alexandrie, Egypte</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2007 - 2017</div>
                        <div class="info">
                            <p class="semi-bold">Expert-Comptable</p>
                            <p>Tareq Hassanein Chartered Accountant Office - Alexandrie, Egypte</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_education">
                <div class="title">
                    <p class="bold"> <i class="fas fa-graduation-cap"></i> Formation</p>
                </div>
                <ul>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Développeur web ( 3W Academy )</p>
                            <p>Développeur Web , Gestion du Web / multimédia et webmaster-Level 5 & EUROPE</p>
                            <p>(Certification développeur-intégrateur dans le développement d'applications Web)</p>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Faculté de Commerce (Université d’Alexandrie)</p>
                            <p>Bachelor commerce (BAC + 4 )</p>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Victory Collège </p>
                            <p>Baccalauréat, Scientifique </p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_hobby">
                <div class="title">
                    <p class="bold"> <i class="fas fa-star"></i> Centres d'intérêt</p>
                </div>
                <ul>
                    <li>
                        <i class="fas fa-book"></i>
                        <p>Lecture</p>
                    </li>
                    <li><i class="fas fa-gamepad"></i>
                        <p>Jeux-vidéos</p>
                    </li>
                    <li><i class="fas fa-music"></i>
                        <p>Musique</p>
                    </li>
                    <li><i class="fas fa-futbol"></i>
                        <p> Football</p>
                    </li>
                    <li><i class="fas fa-plane"></i>
                        <p>Voyage</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</article>
