<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- Favicons -->
    <link href="img/logo.png" rel="icon">
    <title>M.HASSANEIN</title>
    <link rel="stylesheet" href="assets/css/styles.css">
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>

<body class="cv">
    <?php include $template;?>
</body>
<div class="ref">
    <button onclick="window.print()"> <i class="fas fa-print"></i> Print C.V.</button>
    <div class="dropdown">
        <a class="dropbtn" id="lang">lang <i class="fas fa-caret-down"></i> </a>
        <div id="myDropdown" class="dropdown-content">
            <a href="french"> Français</a>
            <a href="english"> English</a>
            <!-- <a href="arabic">Arabic</a> -->
        </div>
    </div>
</div>
<script src="js/script.js"></script>

</html>