<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- Favicons -->
    <link href="assets/img/logo.png" rel="icon">
    <title>M.HASSANEIN</title>
    <link rel="stylesheet" href="assets/css/normalize.css">
    <link rel="stylesheet" href="assets/css/styles.css">
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>

<body>
    <header></header>
    <div class="ref">
        <div class="dropdown">
            <a class=""><i class="fas fa-language dropbtn "></i> </a>
            <div id="myDropdown" class="dropdown-content">
                <a href="french"> Fr</a>
                <a href="english"> En</a>
            </div>
        </div>
        <button onclick="window.print()"> <i class="fas fa-print"></i></button>
    </div>
    <main>
        <?php include $template;?>
    </main>
    <footer></footer>
</body>

<script src="assets/js/script.js"></script>

</html>