<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- Favicons -->
    <link href="assets/img/logo.png" rel="icon">
    <title>M.HASSANEIN</title>
    <link rel="stylesheet" href="assets/css/normalize.css">
    <link rel="stylesheet" href="assets/css/styles.css">
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>

<body>
    <header class="page-header"></header>
    <div class="ref">
        <div class="dropdown">
            <a class=""><i class="fas fa-language dropbtn "></i> </a>
            <div id="myDropdown" class="dropdown-content">
                <a href="french"> Fr</a>
                <a href="english"> En</a>
                <!--   <a href="arabic"> Ar</a> -->
            </div>
        </div>
        <button onclick="window.print()"> <i class="fas fa-print"></i></button>
    </div>
    <main class="page-main" id="dvContainer">
        <?php include $template;?>
    </main>
    <footer class="page-footer"></footer>

</body>
<!-- Template Main JS File -->

<script src="assets/js/script.js"></script>


</html>