<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- Favicons -->
    <link href="img/logo.png" rel="icon">
    <title>M.HASSANEIN</title>
    <link rel="stylesheet" href="css/styles.css">
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>

<body>
    <div class="resume">
        <div class="resume_left">
            <div class='r-hex'>
                <div class='r-hex-inner'>
                    <div class='r-hex-inner-2'></div>
                </div>
            </div>
            <div class="resume_content">
                <div class="resume_item resume_info">
                    <div class="title-name">
                        <p class="bold">Mohammed HASSANEIN</p>
                        <p class="regular">Full Stack Développeur web</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fas fa-map-signs"></i>
                            </div>
                            <div class="data">
                                95 Avenue de la Résistance, Le Raincy<br /> FRANCE
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-mobile-alt"></i>
                            </div>
                            <div class="data">
                                07 67 93 38 18
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-envelope"></i>
                            </div>
                            <div class="data">
                                mohammed.tareq.hassanien@hotmail.com.
                            </div>
                        </li>
                        <!--  <li>
                            <div class="icon">
                                <i class="fab fa-weebly"></i>
                            </div>
                            <div class="data">
                                www.M.HASSSANEIN.DEV.com
                            </div>
                        </li> -->
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold">Compétences</p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                HTML
                            </div>
                            <div class="skill_progress">
                                <span style="width: 100%;"></span>
                            </div>
                            <div class="skill_per">100%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                CSS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 100%;"></span>
                            </div>
                            <div class="skill_per">100%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                SASS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per">90%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                JS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per">85%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                JQUERY
                            </div>
                            <div class="skill_progress">
                                <span style="width: 88%;"></span>
                            </div>
                            <div class="skill_per">88%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                PHP
                            </div>
                            <div class="skill_progress">
                                <span style="width: 100%;"></span>
                            </div>
                            <div class="skill_per">100%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                VUE JS
                            </div>
                            <div class="skill_progress">
                                <span style="width: 85%;"></span>
                            </div>
                            <div class="skill_per">85%</div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold">langues</p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                Arabe
                            </div>
                            <div class="skill_progress">
                                <span style="width: 100%;"></span>
                            </div>
                            <div class="skill_per">100%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Anglais
                            </div>
                            <div class="skill_progress">
                                <span style="width: 95%;"></span>
                            </div>
                            <div class="skill_per">95%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                Français
                            </div>
                            <div class="skill_progress">
                                <span style="width: 90%;"></span>
                            </div>
                            <div class="skill_per">90%</div>
                        </li>
                    </ul>
                </div>

                <div class="resume_item resume_social">
                    <div class="title">
                        <p class="bold">Médias sociaux</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fab fa-facebook-square"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Facebook</p>
                                <a href="https://www.facebook.com/profile.php?id=582452558">Mohammed-Tareq</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-twitter-square"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Twitter</p>
                                <a href="https://twitter.com/momed9999?s=08"> @momed9999</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-instagram"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Instagram</p>
                                <a href="https://www.instagram.com/momed999/">momed999</a>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-linkedin"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Linkedin</p>
                                <a
                                    href="https://www.linkedin.com/in/mohammed-hassanein-4a9b172a">linkedin.com/in/mohammed-hassanein-4a9b172a</a>
                            </div>
                        </li>
                        <li>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="resume_right">
            <div class="resume_item resume_about">
                <div class="title">
                    <p class="bold">À PROPOS </p>
                </div>
                <p> Développeur Web full-stack certifié avec une expérience en HTLM, CSS, JavaScript, PHP, VUE.JS,
                    J.Query et My SQL. Travailles sur l'analyse des besoins des clients, le développement et la
                    conception de la mise
                    en oeuvre des projets .
                </p>
            </div>
            <div class="resume_item resume_work">
                <div class="title">
                    <p class="bold">EXPERIENCES PROFESSIONNELLES</p>
                </div>
                <ul>
                    <li>
                        <div class="date">2020</div>
                        <div class="info">
                            <p class="semi-bold">Full Stack Développeur web </p>
                            <p>3W Academy – Web education– Paris, France</p>
                            <ul class="competence">
                                <li>Analyser les besoins du client .</li>
                                <li>Rédiger une Spécification Technique de Besoin (STB) .</li>
                                <li>Réaliser des études et développements informatiques .</li>
                                <li>Définir les moyens humains, matériels et financiers d'un projet .</li>
                                <li>Établir un cahier des charges .</li>
                                <li>Planifier les étapes d'un projet.</li>
                                <li>Créer et développer une application / site web en lien avec une base de données .
                                </li>
                                <li>Intervenir en informatique de gestion .</li>


                            </ul>
                        </div>
                    </li>
                    <li>
                        <div class="date">2018 - 2019</div>
                        <div class="info">
                            <p class="semi-bold">Directeur Comptable</p>
                            <p>SARL-S.T.F - Paris, France</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2012 - 2017</div>
                        <div class="info">
                            <p class="semi-bold">Directeur Financier</p>
                            <p>LOGISTICS INTERNATIONAL OUTSOURCING NETWORKING SERVICES (LIONS) - Alexandrie, Egypte</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2010 - 2012</div>
                        <div class="info">
                            <p class="semi-bold">Directeur Comptable</p>
                            <p>INTER LOG INTERNATIONAL LOGISTICS - Alexandrie, Egypte</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">2007 - 2017</div>
                        <div class="info">
                            <p class="semi-bold">Expert-Comptable</p>
                            <p>Tareq Hassanein Chartered Accountant Office - Alexandrie, Egypte</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_education">
                <div class="title">
                    <p class="bold">FORMATION</p>
                </div>
                <ul>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Développeur web ( 3W Academy )</p>
                            <p>Développeur Web , Gestion du Web / multimédia et webmaster</p>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Faculté de Commerce (Université d’Alexandrie)</p>
                            <p>Bachelor commerce (BAC + 4 )</p>
                        </div>
                    </li>
                    <li>
                        <div class="date"></div>
                        <div class="info">
                            <p class="semi-bold">Victory Collège </p>
                            <p>Baccalauréat, Scientifique </p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_hobby">
                <div class="title">
                    <p class="bold">CENTRES D’INTERET</p>
                </div>
                <ul>
                    <li><i class="fas fa-book"></i></li>
                    <li><i class="fas fa-gamepad"></i></li>
                    <li><i class="fas fa-music"></i></li>
                    <li><i class="fas fa-futbol"></i></li>
                    <li><i class="fas fa-plane"></i></li>
                </ul>
            </div>
        </div>
    </div>
    <button onclick="window.print()"> <i class="fas fa-print"></i> Print C.V.</button>

</body>


</html>